// Shared question bank data for the Assessment and Question Bank modules.
export const sectionsData = [
  { title: 'Section 1 · Accounting', questions: [
    { text: 'Persamaan dasar akuntansi yang benar adalah...', options: ['Aset = Liabilitas + Ekuitas', 'Aset = Liabilitas \u2212 Ekuitas', 'Ekuitas = Aset + Liabilitas', 'Liabilitas = Aset + Ekuitas'], correct: 0 },
    { text: 'Dalam sistem pencatatan double-entry, setiap transaksi dicatat pada minimal...', options: ['1 akun', '2 akun', '3 akun', '4 akun'], correct: 1 },
    { text: 'Akun yang bersaldo normal debit adalah...', options: ['Liabilitas', 'Ekuitas', 'Aset', 'Pendapatan'], correct: 2 },
    { text: 'Buku yang mencatat transaksi secara kronologis disebut...', options: ['Buku besar', 'Neraca saldo', 'Laporan laba rugi', 'Jurnal umum'], correct: 3 },
    { text: 'Neraca saldo (trial balance) disusun untuk memastikan...', options: ['Total debit sama dengan total kredit', 'Besarnya laba bersih', 'Jumlah kas perusahaan', 'Total aset tetap'], correct: 0 },
    { text: 'Akun kontra aset yang mengurangi nilai aset tetap adalah...', options: ['Kas', 'Akumulasi penyusutan', 'Utang usaha', 'Modal saham'], correct: 1 },
    { text: 'Metode penilaian persediaan yang mengasumsikan barang yang pertama masuk adalah yang pertama keluar disebut...', options: ['LIFO', 'Average', 'FIFO', 'Specific identification'], correct: 2 },
    { text: 'Rumus penyusutan garis lurus (straight-line) adalah...', options: ['(Harga perolehan \u2212 Nilai residu) / Umur ekonomis', 'Harga perolehan / Umur ekonomis', 'Nilai residu / Umur ekonomis', 'Harga perolehan \u00d7 Tarif pajak'], correct: 0 },
    { text: 'Dalam basis akrual, pendapatan diakui pada saat...', options: ['Kas diterima', 'Faktur diterbitkan', 'Diperoleh, terlepas dari kapan kas diterima', 'Akhir tahun buku'], correct: 2 },
    { text: 'Tujuan utama ayat jurnal penyesuaian (adjusting entries) adalah...', options: ['Menutup akun nominal', 'Membuka pembukuan baru', 'Membuat laporan keuangan mencerminkan kondisi sebenarnya sesuai periode', 'Mengoreksi kesalahan kas'], correct: 2 },
    { text: 'Laporan laba rugi mengukur...', options: ['Posisi keuangan pada tanggal tertentu', 'Kinerja keuangan selama periode tertentu', 'Arus kas masuk dan keluar', 'Perubahan ekuitas'], correct: 1 },
    { text: 'Laporan posisi keuangan (neraca) menunjukkan...', options: ['Kinerja selama satu periode', 'Posisi aset, liabilitas, dan ekuitas pada tanggal tertentu', 'Arus kas operasi', 'Perubahan modal kerja'], correct: 1 },
    { text: 'Laporan arus kas terbagi menjadi tiga aktivitas, yaitu...', options: ['Operasi, investasi, dan pendanaan', 'Produksi, distribusi, dan penjualan', 'Kas masuk, kas keluar, dan saldo', 'Debit, kredit, dan saldo'], correct: 0 },
    { text: 'Modal kerja bersih (net working capital) dihitung dari...', options: ['Total aset \u2212 total liabilitas', 'Aset lancar \u2212 liabilitas jangka pendek', 'Aset tetap \u2212 akumulasi penyusutan', 'Ekuitas \u2212 laba ditahan'], correct: 1 },
  ]},
  { title: 'Section 2 · Financial Statement Analysis', questions: [
    { text: 'Rasio lancar (current ratio) dihitung dengan...', options: ['Aset lancar / Liabilitas lancar', 'Kas / Liabilitas lancar', 'Aset lancar / Total aset', 'Laba bersih / Aset lancar'], correct: 0 },
    { text: 'Rasio cepat (quick ratio / acid test) mengeluarkan komponen...', options: ['Kas', 'Piutang', 'Persediaan', 'Investasi jangka pendek'], correct: 2 },
    { text: 'Return on Equity (ROE) dihitung dari...', options: ['Laba bersih / Total aset', 'Laba bersih / Ekuitas', 'Laba kotor / Penjualan', 'Penjualan / Ekuitas'], correct: 1 },
    { text: 'Return on Assets (ROA) mengukur...', options: ['Efisiensi penggunaan ekuitas', 'Efisiensi penggunaan seluruh aset menghasilkan laba', 'Kemampuan membayar utang jangka pendek', 'Margin laba kotor'], correct: 1 },
    { text: 'Rasio yang mengukur proporsi utang terhadap ekuitas adalah...', options: ['Current ratio', 'Debt to Equity Ratio', 'Gross profit margin', 'Inventory turnover'], correct: 1 },
    { text: 'Analisis common-size (vertikal) pada laporan laba rugi menyajikan setiap pos sebagai persentase dari...', options: ['Total aset', 'Total penjualan', 'Laba bersih', 'Total ekuitas'], correct: 1 },
    { text: 'Analisis horizontal (trend) dilakukan dengan cara...', options: ['Membandingkan pos laporan keuangan antar periode', 'Membandingkan pos terhadap total aset', 'Menghitung rata-rata industri', 'Menilai risiko kredit'], correct: 0 },
    { text: 'Gross Profit Margin dihitung dengan...', options: ['Laba kotor / Penjualan', 'Laba bersih / Penjualan', 'Laba kotor / Total aset', 'HPP / Penjualan'], correct: 0 },
    { text: 'Perputaran persediaan (inventory turnover) yang tinggi biasanya mengindikasikan...', options: ['Persediaan menumpuk di gudang', 'Penjualan persediaan berjalan efisien', 'Harga pokok penjualan rendah', 'Piutang tak tertagih tinggi'], correct: 1 },
    { text: 'Days Sales Outstanding (DSO) yang tinggi mengindikasikan...', options: ['Penagihan piutang berjalan cepat', 'Penagihan piutang berjalan lambat', 'Persediaan cepat terjual', 'Utang cepat dilunasi'], correct: 1 },
    { text: 'Analisis Du Pont menguraikan ROE menjadi tiga komponen, yaitu...', options: ['Margin laba, perputaran aset, dan leverage keuangan', 'Likuiditas, solvabilitas, dan profitabilitas', 'Kas, piutang, dan persediaan', 'Pendapatan, beban, dan laba'], correct: 0 },
    { text: 'Earnings per Share (EPS) dihitung dari...', options: ['Laba bersih / Jumlah saham beredar', 'Total ekuitas / Jumlah saham beredar', 'Dividen / Jumlah saham beredar', 'Harga saham / Laba bersih'], correct: 0 },
    { text: 'Interest Coverage Ratio mengukur...', options: ['Kemampuan membayar pokok utang', 'Kemampuan membayar beban bunga dari laba operasional', 'Kemampuan membayar dividen', 'Kemampuan membiayai investasi'], correct: 1 },
  ]},
  { title: 'Section 3 · Risk Based Audit', questions: [
    { text: 'Pendekatan audit berbasis risiko (risk-based audit) memfokuskan sumber daya audit pada...', options: ['Seluruh transaksi tanpa kecuali', 'Area dengan risiko salah saji material tertinggi', 'Transaksi bernilai kecil', 'Akun yang mudah diperiksa'], correct: 1 },
    { text: 'Risiko audit terdiri dari tiga komponen, yaitu...', options: ['Risiko inheren, risiko pengendalian, dan risiko deteksi', 'Risiko pasar, risiko kredit, dan risiko operasional', 'Risiko strategis, risiko hukum, dan risiko reputasi', 'Risiko likuiditas, risiko bunga, dan risiko valuta'], correct: 0 },
    { text: 'Risiko inheren adalah...', options: ['Risiko akibat kegagalan pengendalian internal', 'Kerentanan suatu asersi terhadap salah saji sebelum mempertimbangkan pengendalian internal', 'Risiko auditor gagal mendeteksi salah saji', 'Risiko reputasi entitas'], correct: 1 },
    { text: 'Risiko pengendalian (control risk) adalah risiko bahwa...', options: ['Auditor gagal mendeteksi salah saji', 'Pengendalian internal gagal mencegah atau mendeteksi salah saji secara tepat waktu', 'Transaksi dicatat dua kali', 'Laporan keuangan terlambat terbit'], correct: 1 },
    { text: 'Risiko deteksi (detection risk) adalah risiko bahwa...', options: ['Manajemen melakukan kecurangan', 'Pengendalian internal tidak berjalan', 'Prosedur audit gagal mendeteksi salah saji material yang ada', 'Auditor kehilangan independensi'], correct: 2 },
    { text: 'Materialitas dalam audit ditetapkan untuk...', options: ['Menentukan jumlah sampel secara acak', 'Menentukan signifikansi suatu salah saji terhadap laporan keuangan', 'Menghitung fee audit', 'Menentukan lama waktu audit'], correct: 1 },
    { text: 'Uji pengendalian (test of control) bertujuan untuk...', options: ['Menilai efektivitas operasi suatu pengendalian internal', 'Menghitung saldo akun secara langsung', 'Mengonfirmasi saldo ke pihak ketiga', 'Menelusuri dokumen sumber'], correct: 0 },
    { text: 'Uji substantif (substantive test) bertujuan untuk...', options: ['Menilai desain pengendalian', 'Mendeteksi salah saji material pada saldo akun atau transaksi', 'Mengukur budaya risiko organisasi', 'Menyusun audit universe'], correct: 1 },
    { text: 'Model tiga lini pertahanan (three lines model) dalam manajemen risiko terdiri dari...', options: ['Manajemen operasional, fungsi manajemen risiko dan kepatuhan, serta audit internal', 'Dewan komisaris, direksi, dan pemegang saham', 'Auditor eksternal, regulator, dan manajemen', 'Front office, middle office, dan back office'], correct: 0 },
    { text: 'Root cause analysis dalam audit digunakan untuk...', options: ['Menghitung skor risiko', 'Mengidentifikasi penyebab mendasar dari suatu temuan audit', 'Menentukan sampel audit', 'Menyusun laporan keuangan'], correct: 1 },
    { text: 'Risk appetite adalah...', options: ['Tingkat risiko yang bersedia diterima organisasi dalam mencapai tujuannya', 'Daftar seluruh risiko yang pernah terjadi', 'Batas maksimum kerugian yang diasuransikan', 'Skor risiko tertinggi dalam audit universe'], correct: 0 },
    { text: 'Audit universe adalah...', options: ['Standar audit internasional', 'Daftar seluruh area atau entitas yang berpotensi menjadi objek audit', 'Rencana audit tahunan yang telah disetujui', 'Kertas kerja auditor'], correct: 1 },
    { text: 'Dalam sampling audit berbasis risiko, alokasi sampel yang lebih besar diberikan pada...', options: ['Area dengan risiko tinggi', 'Area dengan nilai transaksi terkecil', 'Area yang sudah diaudit tahun lalu', 'Area yang dipilih secara acak'], correct: 0 },
  ]},
];
